admin:
    defaults:
        _controller:                    SvdCoreBundle:Redirect:admin
    methods:                            [DELETE, GET, POST, PUT]
    path:                               /admin
