admin:
    path:                               /admin
    defaults:
        _controller:                    SvdCoreBundle:Redirect:admin
    requirements:
        _method:                        DELETE|GET|POST|PUT
