default:
    defaults:
        _controller:                    SvdCoreBundle:Redirect:default
    methods:                            [DELETE, GET, POST, PUT]
    path:                               /
