pong:
    path:                               /pong
    defaults:
        _controller:                    SvdCoreBundle:Check:pong
    requirements:
        _method:                        DELETE|GET|POST|PUT
